# Generated by Django 4.1.5 on 2023-01-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='tabel.person', verbose_name='член бригады')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='tabel.person', verbose_name='руководитель бригады')),
            ],
            options={
                'verbose_name': 'Состав бригады',
                'verbose_name_plural': 'Состав бригады',
                'ordering': ['supervisor'],
            },
        ),
    ]
