# Generated by Django 4.1.5 on 2023-01-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0002_brigades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabel',
            new_name='TabelRecord',
        ),
    ]
