# Generated by Django 4.1.5 on 2023-01-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0002_worktype_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='work_time',
            field=models.FloatField(blank=True, verbose_name='Время работы'),
        ),
    ]
