# Generated by Django 4.1.5 on 2023-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0003_alter_tabel_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='work_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Время работы'),
        ),
    ]
