# Generated by Django 4.1.5 on 2023-01-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0004_alter_tabel_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='combination',
            field=models.FloatField(blank=True, null=True, verbose_name='Совмещение'),
        ),
        migrations.AddField(
            model_name='tabel',
            name='harmfulness',
            field=models.BooleanField(default=False, verbose_name='Вредность'),
        ),
        migrations.AddField(
            model_name='tabel',
            name='siding',
            field=models.BooleanField(default=False, verbose_name='Разъезд'),
        ),
        migrations.AddField(
            model_name='tabel',
            name='transferred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferred', to='tabel.person', verbose_name='Передан'),
        ),
        migrations.AddField(
            model_name='tabel',
            name='work_foreman',
            field=models.BooleanField(default=False, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='tabel.person', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabel.worktype', verbose_name='Причина отсутствия'),
        ),
    ]
