# Generated by Django 4.1.5 on 2023-01-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0005_tabel_combination_tabel_harmfulness_tabel_siding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='tabel.person', verbose_name='Мастер'),
        ),
    ]
